name: CI

on: [push]

jobs:
  build-compiler:

    name: Build compiler release
    runs-on: ubuntu-latest
    needs: [test-compiler-linux, test-compiler-windows]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '5.0'

    - name: Install dependencies
      run: dotnet restore
      working-directory: src/compiler

    - name: Build
      run: dotnet publish --configuration Release --no-restore -o ./output
      working-directory: src/compiler

    - name: Archive build result
      uses: actions/upload-artifact@v2
      with:
        name: compiler
        path: src/compiler/output

  test-compiler-linux:

    name: Test compiler on linux
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '5.0'

    - name: Install dependencies
      run: dotnet restore
      working-directory: src/compiler

    - name: Test
      run: dotnet test --no-restore
      working-directory: src/compiler

  test-compiler-windows:
    name: Test compiler on windows
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '5.0'

    - name: Install dependencies
      run: dotnet restore
      working-directory: src/compiler

    - name: Test
      run: dotnet test --no-restore
      working-directory: src/compiler

  build-vscode-extension:

    name: Build VSCode extension
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '15.0'

    - name: Install dependencies
      run: npm ci
      working-directory: src/vscode-extension

    - name: Build
      run: npm run compile
      working-directory: src/vscode-extension