name: CI

on: [push]

jobs:
  build-compiler-linux:

    name: Build linux binaries
    runs-on: ubuntu-latest
    needs: [test-compiler-linux, test-compiler-windows]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0'

    - name: Install dependencies
      run: dotnet restore
      working-directory: src/compiler

    - name: Build
      run: dotnet publish Lucy.App/Lucy.App.csproj --configuration Release --no-restore --framework net7.0 -o ./output
      working-directory: src/compiler

    - name: Archive build result
      uses: actions/upload-artifact@v3
      with:
        name: binaries-linux
        path: src/compiler/output

  build-compiler-windows:

    name: Build windows binaries
    runs-on: windows-latest
    needs: [test-compiler-linux, test-compiler-windows]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0'

    - name: Install dependencies
      run: dotnet restore
      working-directory: src/compiler

    - name: Build
      run: dotnet publish Lucy.App/Lucy.App.csproj --configuration Release --no-restore --framework net7.0 -o ./output
      working-directory: src/compiler

    - name: Archive build result
      uses: actions/upload-artifact@v3
      with:
        name: binaries-linux
        path: src/compiler/output

  test-compiler-linux:

    name: Test compiler on linux
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0'

    - name: Install dependencies
      run: dotnet restore
      working-directory: src/compiler

    - name: Test
      run: dotnet test --no-restore
      working-directory: src/compiler

  test-compiler-windows:
    name: Test compiler on windows
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0'

    - name: Install dependencies
      run: dotnet restore
      working-directory: src/compiler

    - name: Test
      run: dotnet test --no-restore
      working-directory: src/compiler

  build-vscode-extension:

    name: Build VSCode extension
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '18.14.0'

    - name: Install dependencies
      run: npm ci
      working-directory: src/vscode-extension

    - name: Build
      run: npm run compile
      working-directory: src/vscode-extension