name: CI

on: [push]

jobs:
  build-compiler-linux:

    name: Build and test linux binaries
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0'

    - name: Install dependencies
      run: dotnet restore
      working-directory: src/compiler

    - name: Test
      run: dotnet test --no-restore
      working-directory: src/compiler

    - name: Publish
      run: dotnet publish Lucy.App/Lucy.App.csproj --configuration Release --no-restore --framework net7.0 -o ./output
      working-directory: src/compiler

    - name:  Upload artefact
      uses: actions/upload-artifact@v3
      with:
        name: binaries-linux
        path: src/compiler/output

  build-compiler-windows:

    name: Build and test windows binaries
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0'

    - name: Install dependencies
      run: dotnet restore
      working-directory: src/compiler

    - name: Test
      run: dotnet test --no-restore
      working-directory: src/compiler

    - name: Publish
      run: dotnet publish Lucy.App/Lucy.App.csproj --configuration Release --no-restore --framework net7.0 -o ./output
      working-directory: src/compiler

    - name: Upload artefact
      uses: actions/upload-artifact@v3
      with:
        name: binaries-windows
        path: src/compiler/output

  build-vscode-extension:

    name: Build VSCode extension
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '18.14.0'

    - name: Install dependencies
      run: npm ci
      working-directory: src/vscode-extension

    - name: Build
      run: npm run compile
      working-directory: src/vscode-extension